<?php

namespace App\Console\Commands;

use App\Enums\Locale;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

#[Signature('app:generate-translation-types')]
#[Description('Generate TypeScript types from lang PHP translation files')]
class GenerateTranslationTypes extends Command
{
    public function handle(): int
    {
        $langPath = lang_path(Locale::EN->value);

        if (! File::isDirectory($langPath)) {
            $this->error("Lang directory not found: {$langPath}");

            return self::FAILURE;
        }

        $phpFiles = array_filter(
            File::allFiles($langPath),
            fn ($f) => $f->getExtension() === 'php'
        );

        if (empty($phpFiles)) {
            $this->warn("No PHP translation files found in {$langPath}");

            return self::SUCCESS;
        }

        $typesPath = resource_path('js/types');
        $translationsPath = "{$typesPath}/translations";

        File::ensureDirectoryExists($typesPath);
        File::ensureDirectoryExists($translationsPath);

        foreach ($phpFiles as $file) {
            $translations = include $file->getPathname();

            if (! is_array($translations)) {
                $this->warn("Skipping {$file->getRelativePathname()} — does not return an array.");

                continue;
            }

            $relativePath = $file->getRelativePathname();                     // public/settings/user.php
            $withoutExt = Str::beforeLast($relativePath, '.php');          // public/settings/user
            $normalized = str_replace(['/', '\\', '-'], ' ', $withoutExt); // public settings user
            $typeName = Str::studly($normalized);                        // PublicSettingsUser

            $outPath = "{$translationsPath}/{$withoutExt}.ts";               // types/translations/public/settings/user.ts

            File::ensureDirectoryExists(dirname($outPath));

            if (File::exists($outPath)) {
                File::delete($outPath);
            }

            $lines = [];
            $lines[] = '// Auto-generated by `php artisan translations:types` — do not edit manually.';
            $lines[] = '';
            $lines[] = "export type {$typeName}Translations = {";
            $this->appendTypeLines($lines, $translations, indent: 1);
            $lines[] = '};';

            File::put($outPath, implode(PHP_EOL, $lines));

            $this->line("✓ {$relativePath} → types/translations/{$withoutExt}.ts");
        }

        $this->info('✓ TypeScript types generated.');

        return self::SUCCESS;
    }

    private function appendTypeLines(array &$lines, array $translations, int $indent): void
    {
        $pad = str_repeat('    ', $indent);

        foreach ($translations as $key => $value) {
            if (is_array($value) && empty($value)) {
                continue;
            }

            $safeKey = preg_match('/[^a-zA-Z0-9_]/', (string) $key)
                ? '"'.$key.'"'
                : $key;

            if (is_array($value)) {
                $lines[] = "{$pad}{$safeKey}: {";
                $this->appendTypeLines($lines, $value, $indent + 1);
                $lines[] = "{$pad}};";
            } else {
                $lines[] = "{$pad}{$safeKey}: string;";
            }
        }
    }
}
