// Auto-generated by `php artisan translations:types` — do not edit manually.

export type PublicIndexTranslations = {
    page_title: string;
    page_description: string;
    proceed_to_application: string;
};