// Auto-generated by `php artisan translations:types` — do not edit manually.

export type PublicLoginTranslations = {
    layout: {
        title: string;
        description: string;
    };
    page_description: string;
    page_title: string;
    email_label: string;
    email_aria: string;
    email_placeholder: string;
    password_placeholder: string;
    remember_me: string;
    sign_in: string;
    separator_or: string;
    create_account: string;
    continue_facebook: string;
    continue_google: string;
    continue_apple: string;
};