// Auto-generated by `php artisan translations:types` — do not edit manually.

export type PublicRegisterTranslations = {
    layout: {
        title: string;
        description: string;
    };
    page_title: string;
    name_label: string;
    name_aria: string;
    name_placeholder: string;
    email_label: string;
    email_aria: string;
    email_placeholder: string;
    password_label: string;
    password_placeholder: string;
    forgot_password_label: string;
    confirm_password_label: string;
    confirm_password_placeholder: string;
    create_account: string;
    already_have_account: string;
    log_in: string;
};