// Auto-generated by `php artisan translations:types` — do not edit manually.

export type PublicPasswordRequestTranslations = {
    layout: {
        title: string;
        description: string;
    };
    page_title: string;
    email_label: string;
    email_aria: string;
    email_placeholder: string;
    email_password_reset_link: string;
    return_or_prefix: string;
    log_in: string;
};