// Auto-generated by `php artisan translations:types` — do not edit manually.

export type PublicPasswordResetTranslations = {
    layout: {
        title: string;
        description: string;
    };
    page_title: string;
    email_label: string;
    email_aria: string;
    password_label: string;
    password_placeholder: string;
    forgot_password_label: string;
    confirm_password_label: string;
    confirm_password_placeholder: string;
    reset_password: string;
};