// Auto-generated by `php artisan translations:types` — do not edit manually.

export type PasswordsTranslations = {
    reset: string;
    sent: string;
    throttled: string;
    token: string;
    user: string;
};