// Auto-generated by `php artisan translations:types` — do not edit manually.

export type AppVerificationNoticeTranslations = {
    page_title: string;
    heading_title: string;
    heading_description: string;
    status_verification_link_sent: string;
    resend_verification_email: string;
    log_out: string;
    breadcrumb_title: string;
};